name: big-bear-portainer
services:
    app:
        cpu_shares: 90
        command: []
        container_name: portainer
        deploy:
            resources:
                limits:
                    memory: "16609443840"
        hostname: portainer
        image: portainer/portainer-ce:2.31.1-alpine
        labels:
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/portainer.png
        networks:
            dora-network: null
        ports:
            - mode: ingress
              target: 8000
              published: "8000"
              protocol: tcp
            - mode: ingress
              target: 9000
              published: "9000"
              protocol: tcp
            - target: 9443
              published: "9443"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/big-bear-portainer/data
              target: /data
              bind:
                create_host_path: true
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
              bind:
                create_host_path: true
        x-casaos:
            ports:
                - container: "8000"
                  description:
                    en_us: 'Container: 8000'
                - container: "9000"
                  description:
                    en_us: 'Container: 9000'
                - container: "9443"
                  description:
                    en_us: 'Container: 9443'
            volumes:
                - container: /data
                  description:
                    en_us: Access to Portainer data
                - container: /var/run/docker.sock
                  description:
                    en_us: Access to Docker socket
networks:
    dora-network:
        name: dora-network
x-casaos:
    architectures:
        - amd64
        - arm64
    author: BigBearTechWorld
    category: BigBearCasaOS
    description:
        en_us: Irrespective of your industry, orchestration platform, or computing device, Portainer is the most versatile container management software that simplifies your secure adoption of containers with remarkable speed.
    developer: portainer
    hostname: portainer.dadora.casa
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/portainer.png
    index: /
    is_uncontrolled: false
    main: app
    port_map: ""
    scheme: https
    store_app_id: big-bear-portainer
    tagline:
        en_us: Portainer
    thumbnail: ""
    title:
        custom: ""
        en_us: Portainer
